name: cloudflare-hook
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  hook:
    runs-on: ubuntu-latest
    steps:
      - name: hook
        uses: cloudflare/wrangler-action@1.1.0
        run:
          curl -X POST ${{ secrets.CLOUD_FLARE_BUILD_URL }}
